baseURL = "https://devgost.com"
languageCode = "en"
DefaultContentLanguage = "en"
#title = "DevGost"
# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"


[params]
contentratio = 0.7
mainSections = ["post"]

#Languages
[Languages]
  [Languages.en]
  title = "DevGost"
  contentDir = "content/english"
  Weight = 1
  LanguageName = "EN"

    [[Languages.en.menu.main]]
    url = "/"
    identifier = "home"
    name = "Home"
    weight = 100
    [[Languages.en.menu.main]]
    url = "/post/"
    identifier = "post"
    name = "Blog"
    weight = 200
    [[Languages.en.menu.main]]
    url = "/about/"
    identifier = "About"
    name = "About"
    weight = 300


  [Languages.fi]
  title = "DevGost"
  contentDir = "content/finnish"
  Weight = 2
  LanguageName = "FI"
    [[Languages.fi.menu.main]]
    url = "/fi/"
    identifier = "koti"
    name = "koti"
    weight = 100
    [[Languages.fi.menu.main]]
    url = "/fi/post/"
    identifier = "Blogi"
    name = "Blogi"
    weight = 200
    [[Languages.fi.menu.main]]
    url = "/fi/about/"
    identifier = "Tietoa minusta"
    name = "About"
    weight = 300




summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

